// import 'entities/pet_entity.dart';
//
// final List<PetEntity> mockPets = [
//   PetEntity(
//     id: '1',
//     name: 'Charlie',
//     type: 'Dog',
//     breed: 'Labrador Retriever',
//     age: '2 years',
//     price: 300.0,
//     gender: 'Male',
//     imageUrl: 'https://images.unsplash.com/photo-1558788353-f76d92427f16',
//     location: 'Delhi, India',
//     description: 'Friendly and loyal, great with kids and other pets.',
//   ),
//   PetEntity(
//     id: '2',
//     name: 'Luna',
//     type: 'Cat',
//     breed: 'Siamese',
//     age: '1.5 years',
//     price: 200.0,
//     gender: 'Female',
//     imageUrl: 'https://images.unsplash.com/photo-1592194996308-7b43878e84a6',
//     location: 'Mumbai, India',
//     description: 'Elegant and affectionate cat, loves to cuddle.',
//     isFavorited: true,
//   ),
//   PetEntity(
//     id: '3',
//     name: 'Max',
//     type: 'Dog',
//     breed: 'German Shepherd',
//     age: '3 years',
//     price: 350.0,
//     gender: 'Male',
//     imageUrl: 'https://images.unsplash.com/photo-1568572933382-74d440642117',
//     location: 'Bangalore, India',
//     description: 'Very intelligent and protective. Ideal for security.',
//   ),
//   PetEntity(
//     id: '4',
//     name: 'Bella',
//     type: 'Dog',
//     breed: 'Golden Retriever',
//     age: '2.5 years',
//     price: 320.0,
//     gender: 'Female',
//     imageUrl: 'https://images.unsplash.com/photo-1507146426996-ef05306b995a',
//     location: 'Hyderabad, India',
//     description: 'Playful and affectionate, great with families.',
//     isAdopted: true,
//   ),
//   PetEntity(
//     id: '5',
//     name: 'Simba',
//     type: 'Cat',
//     breed: 'Persian',
//     age: '4 years',
//     price: 250.0,
//     gender: 'Male',
//     imageUrl: 'https://images.unsplash.com/photo-1592194996308-7b43878e84a6',
//     location: 'Chennai, India',
//     description: 'Charming and fluffy, enjoys attention and grooming.',
//   ),
//   PetEntity(
//     id: '6',
//     name: 'Coco',
//     type: 'Dog',
//     breed: 'Pomeranian',
//     age: '1 year',
//     price: 150.0,
//     gender: 'Female',
//     imageUrl: 'https://images.unsplash.com/photo-1598137260842-2614dd6c6dfd',
//     location: 'Pune, India',
//     description: 'Small and lively, perfect for apartment living.',
//     isFavorited: true,
//   ),
// ];
